# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Printing Folders
              run: ls -la
