# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: "Use cache for the build"
                type: boolean
                default: true
            node-version:
                description: "Node version to use for caching"
                type: choice
                options: [18.x, 20.x, 21.x]
                default: 20.x
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ github.event.inputs.node-version }}
            - name: Download cached dependencies
              id: cache
              if: ${{ github.event.inputs.use-cache }}
              uses: actions/cache@v3
              with:
                key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
                path: 13-caching/react-app/node_modules

            - name: Install dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to non-production environment"